// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class Attachments extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.Attachments";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Attachments_Lead("Main.Attachments_Lead"),
		Attachments_DocumentTitle("Main.Attachments_DocumentTitle");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Attachments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Attachments(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject attachmentsMendixObject)
	{
		super(context, attachmentsMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, attachmentsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'Attachments.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static main.proxies.Attachments initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.Attachments.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static main.proxies.Attachments initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.Attachments(context, mendixObject);
	}

	public static main.proxies.Attachments load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.Attachments.initialize(context, mendixObject);
	}

	public static java.util.List<main.proxies.Attachments> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> main.proxies.Attachments.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Attachments_Lead
	 */
	public final main.proxies.Lead getAttachments_Lead() throws com.mendix.core.CoreException
	{
		return getAttachments_Lead(getContext());
	}

	/**
	 * @param context
	 * @return value of Attachments_Lead
	 * @throws com.mendix.core.CoreException
	 */
	public final main.proxies.Lead getAttachments_Lead(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Lead result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Attachments_Lead.toString());
		if (identifier != null) {
			result = main.proxies.Lead.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Attachments_Lead
	 * @param attachments_lead
	 */
	public final void setAttachments_Lead(main.proxies.Lead attachments_lead)
	{
		setAttachments_Lead(getContext(), attachments_lead);
	}

	/**
	 * Set value of Attachments_Lead
	 * @param context
	 * @param attachments_lead
	 */
	public final void setAttachments_Lead(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Lead attachments_lead)
	{
		if (attachments_lead == null) {
			getMendixObject().setValue(context, MemberNames.Attachments_Lead.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Attachments_Lead.toString(), attachments_lead.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Attachments_DocumentTitle
	 */
	public final main.proxies.DocumentTitle getAttachments_DocumentTitle() throws com.mendix.core.CoreException
	{
		return getAttachments_DocumentTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Attachments_DocumentTitle
	 * @throws com.mendix.core.CoreException
	 */
	public final main.proxies.DocumentTitle getAttachments_DocumentTitle(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.DocumentTitle result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Attachments_DocumentTitle.toString());
		if (identifier != null) {
			result = main.proxies.DocumentTitle.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Attachments_DocumentTitle
	 * @param attachments_documenttitle
	 */
	public final void setAttachments_DocumentTitle(main.proxies.DocumentTitle attachments_documenttitle)
	{
		setAttachments_DocumentTitle(getContext(), attachments_documenttitle);
	}

	/**
	 * Set value of Attachments_DocumentTitle
	 * @param context
	 * @param attachments_documenttitle
	 */
	public final void setAttachments_DocumentTitle(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.DocumentTitle attachments_documenttitle)
	{
		if (attachments_documenttitle == null) {
			getMendixObject().setValue(context, MemberNames.Attachments_DocumentTitle.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Attachments_DocumentTitle.toString(), attachments_documenttitle.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.Attachments that = (main.proxies.Attachments) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
