// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class InvolvedParties
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject involvedPartiesMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.InvolvedParties";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		HostEnabled("HostEnabled"),
		InviteeEnabled("InviteeEnabled"),
		PartneringType("PartneringType");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public InvolvedParties(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected InvolvedParties(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject involvedPartiesMendixObject)
	{
		if (involvedPartiesMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, involvedPartiesMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.involvedPartiesMendixObject = involvedPartiesMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'InvolvedParties.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static main.proxies.InvolvedParties initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.InvolvedParties.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static main.proxies.InvolvedParties initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.InvolvedParties(context, mendixObject);
	}

	public static main.proxies.InvolvedParties load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.InvolvedParties.initialize(context, mendixObject);
	}

	public static java.util.List<main.proxies.InvolvedParties> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> main.proxies.InvolvedParties.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of HostEnabled
	 */
	public final java.lang.Boolean getHostEnabled()
	{
		return getHostEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of HostEnabled
	 */
	public final java.lang.Boolean getHostEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HostEnabled.toString());
	}

	/**
	 * Set value of HostEnabled
	 * @param hostenabled
	 */
	public final void setHostEnabled(java.lang.Boolean hostenabled)
	{
		setHostEnabled(getContext(), hostenabled);
	}

	/**
	 * Set value of HostEnabled
	 * @param context
	 * @param hostenabled
	 */
	public final void setHostEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hostenabled)
	{
		getMendixObject().setValue(context, MemberNames.HostEnabled.toString(), hostenabled);
	}

	/**
	 * @return value of InviteeEnabled
	 */
	public final java.lang.Boolean getInviteeEnabled()
	{
		return getInviteeEnabled(getContext());
	}

	/**
	 * @param context
	 * @return value of InviteeEnabled
	 */
	public final java.lang.Boolean getInviteeEnabled(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.InviteeEnabled.toString());
	}

	/**
	 * Set value of InviteeEnabled
	 * @param inviteeenabled
	 */
	public final void setInviteeEnabled(java.lang.Boolean inviteeenabled)
	{
		setInviteeEnabled(getContext(), inviteeenabled);
	}

	/**
	 * Set value of InviteeEnabled
	 * @param context
	 * @param inviteeenabled
	 */
	public final void setInviteeEnabled(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean inviteeenabled)
	{
		getMendixObject().setValue(context, MemberNames.InviteeEnabled.toString(), inviteeenabled);
	}

	/**
	 * Set value of PartneringType
	 * @param partneringtype
	 */
	public final main.proxies.PartneringTypeEnum getPartneringType()
	{
		return getPartneringType(getContext());
	}

	/**
	 * @param context
	 * @return value of PartneringType
	 */
	public final main.proxies.PartneringTypeEnum getPartneringType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.PartneringType.toString());
		if (obj == null) {
			return null;
		}
		return main.proxies.PartneringTypeEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of PartneringType
	 * @param partneringtype
	 */
	public final void setPartneringType(main.proxies.PartneringTypeEnum partneringtype)
	{
		setPartneringType(getContext(), partneringtype);
	}

	/**
	 * Set value of PartneringType
	 * @param context
	 * @param partneringtype
	 */
	public final void setPartneringType(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.PartneringTypeEnum partneringtype)
	{
		if (partneringtype != null) {
			getMendixObject().setValue(context, MemberNames.PartneringType.toString(), partneringtype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.PartneringType.toString(), null);
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return involvedPartiesMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.InvolvedParties that = (main.proxies.InvolvedParties) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
