// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class Lead
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject leadMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.Lead";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		Description("Description"),
		ProbabilityReason("ProbabilityReason"),
		RevenueForecast("RevenueForecast"),
		SubmittedBIDPrice("SubmittedBIDPrice"),
		TimelineBCD("TimelineBCD"),
		TimelineExpectedInternalBCD("TimelineExpectedInternalBCD"),
		TimelineExpectedAwardDate("TimelineExpectedAwardDate"),
		TimelineExcpectedExcutionStartDate("TimelineExcpectedExcutionStartDate"),
		TimelineExpectedExecutionEndDate("TimelineExpectedExecutionEndDate"),
		TimelineExcpectedDuration("TimelineExcpectedDuration"),
		SN("SN"),
		TryStatus("TryStatus"),
		Lead_Scope("Main.Lead_Scope"),
		Lead_Probability("Main.Lead_Probability"),
		Lead_ProjectOwner("Main.Lead_ProjectOwner"),
		Lead_ContractType("Main.Lead_ContractType"),
		Lead_Industry("Main.Lead_Industry"),
		Lead_Status("Main.Lead_Status");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Lead(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Lead(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject leadMendixObject)
	{
		if (leadMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, leadMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.leadMendixObject = leadMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Lead.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static main.proxies.Lead initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.Lead.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static main.proxies.Lead initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.Lead(context, mendixObject);
	}

	public static main.proxies.Lead load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.Lead.initialize(context, mendixObject);
	}

	public static java.util.List<main.proxies.Lead> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> main.proxies.Lead.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of ProbabilityReason
	 */
	public final java.lang.String getProbabilityReason()
	{
		return getProbabilityReason(getContext());
	}

	/**
	 * @param context
	 * @return value of ProbabilityReason
	 */
	public final java.lang.String getProbabilityReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ProbabilityReason.toString());
	}

	/**
	 * Set value of ProbabilityReason
	 * @param probabilityreason
	 */
	public final void setProbabilityReason(java.lang.String probabilityreason)
	{
		setProbabilityReason(getContext(), probabilityreason);
	}

	/**
	 * Set value of ProbabilityReason
	 * @param context
	 * @param probabilityreason
	 */
	public final void setProbabilityReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String probabilityreason)
	{
		getMendixObject().setValue(context, MemberNames.ProbabilityReason.toString(), probabilityreason);
	}

	/**
	 * @return value of RevenueForecast
	 */
	public final java.math.BigDecimal getRevenueForecast()
	{
		return getRevenueForecast(getContext());
	}

	/**
	 * @param context
	 * @return value of RevenueForecast
	 */
	public final java.math.BigDecimal getRevenueForecast(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.RevenueForecast.toString());
	}

	/**
	 * Set value of RevenueForecast
	 * @param revenueforecast
	 */
	public final void setRevenueForecast(java.math.BigDecimal revenueforecast)
	{
		setRevenueForecast(getContext(), revenueforecast);
	}

	/**
	 * Set value of RevenueForecast
	 * @param context
	 * @param revenueforecast
	 */
	public final void setRevenueForecast(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal revenueforecast)
	{
		getMendixObject().setValue(context, MemberNames.RevenueForecast.toString(), revenueforecast);
	}

	/**
	 * @return value of SubmittedBIDPrice
	 */
	public final java.math.BigDecimal getSubmittedBIDPrice()
	{
		return getSubmittedBIDPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of SubmittedBIDPrice
	 */
	public final java.math.BigDecimal getSubmittedBIDPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.SubmittedBIDPrice.toString());
	}

	/**
	 * Set value of SubmittedBIDPrice
	 * @param submittedbidprice
	 */
	public final void setSubmittedBIDPrice(java.math.BigDecimal submittedbidprice)
	{
		setSubmittedBIDPrice(getContext(), submittedbidprice);
	}

	/**
	 * Set value of SubmittedBIDPrice
	 * @param context
	 * @param submittedbidprice
	 */
	public final void setSubmittedBIDPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal submittedbidprice)
	{
		getMendixObject().setValue(context, MemberNames.SubmittedBIDPrice.toString(), submittedbidprice);
	}

	/**
	 * @return value of TimelineBCD
	 */
	public final java.util.Date getTimelineBCD()
	{
		return getTimelineBCD(getContext());
	}

	/**
	 * @param context
	 * @return value of TimelineBCD
	 */
	public final java.util.Date getTimelineBCD(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.TimelineBCD.toString());
	}

	/**
	 * Set value of TimelineBCD
	 * @param timelinebcd
	 */
	public final void setTimelineBCD(java.util.Date timelinebcd)
	{
		setTimelineBCD(getContext(), timelinebcd);
	}

	/**
	 * Set value of TimelineBCD
	 * @param context
	 * @param timelinebcd
	 */
	public final void setTimelineBCD(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timelinebcd)
	{
		getMendixObject().setValue(context, MemberNames.TimelineBCD.toString(), timelinebcd);
	}

	/**
	 * @return value of TimelineExpectedInternalBCD
	 */
	public final java.util.Date getTimelineExpectedInternalBCD()
	{
		return getTimelineExpectedInternalBCD(getContext());
	}

	/**
	 * @param context
	 * @return value of TimelineExpectedInternalBCD
	 */
	public final java.util.Date getTimelineExpectedInternalBCD(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.TimelineExpectedInternalBCD.toString());
	}

	/**
	 * Set value of TimelineExpectedInternalBCD
	 * @param timelineexpectedinternalbcd
	 */
	public final void setTimelineExpectedInternalBCD(java.util.Date timelineexpectedinternalbcd)
	{
		setTimelineExpectedInternalBCD(getContext(), timelineexpectedinternalbcd);
	}

	/**
	 * Set value of TimelineExpectedInternalBCD
	 * @param context
	 * @param timelineexpectedinternalbcd
	 */
	public final void setTimelineExpectedInternalBCD(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timelineexpectedinternalbcd)
	{
		getMendixObject().setValue(context, MemberNames.TimelineExpectedInternalBCD.toString(), timelineexpectedinternalbcd);
	}

	/**
	 * @return value of TimelineExpectedAwardDate
	 */
	public final java.util.Date getTimelineExpectedAwardDate()
	{
		return getTimelineExpectedAwardDate(getContext());
	}

	/**
	 * @param context
	 * @return value of TimelineExpectedAwardDate
	 */
	public final java.util.Date getTimelineExpectedAwardDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.TimelineExpectedAwardDate.toString());
	}

	/**
	 * Set value of TimelineExpectedAwardDate
	 * @param timelineexpectedawarddate
	 */
	public final void setTimelineExpectedAwardDate(java.util.Date timelineexpectedawarddate)
	{
		setTimelineExpectedAwardDate(getContext(), timelineexpectedawarddate);
	}

	/**
	 * Set value of TimelineExpectedAwardDate
	 * @param context
	 * @param timelineexpectedawarddate
	 */
	public final void setTimelineExpectedAwardDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timelineexpectedawarddate)
	{
		getMendixObject().setValue(context, MemberNames.TimelineExpectedAwardDate.toString(), timelineexpectedawarddate);
	}

	/**
	 * @return value of TimelineExcpectedExcutionStartDate
	 */
	public final java.util.Date getTimelineExcpectedExcutionStartDate()
	{
		return getTimelineExcpectedExcutionStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of TimelineExcpectedExcutionStartDate
	 */
	public final java.util.Date getTimelineExcpectedExcutionStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.TimelineExcpectedExcutionStartDate.toString());
	}

	/**
	 * Set value of TimelineExcpectedExcutionStartDate
	 * @param timelineexcpectedexcutionstartdate
	 */
	public final void setTimelineExcpectedExcutionStartDate(java.util.Date timelineexcpectedexcutionstartdate)
	{
		setTimelineExcpectedExcutionStartDate(getContext(), timelineexcpectedexcutionstartdate);
	}

	/**
	 * Set value of TimelineExcpectedExcutionStartDate
	 * @param context
	 * @param timelineexcpectedexcutionstartdate
	 */
	public final void setTimelineExcpectedExcutionStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timelineexcpectedexcutionstartdate)
	{
		getMendixObject().setValue(context, MemberNames.TimelineExcpectedExcutionStartDate.toString(), timelineexcpectedexcutionstartdate);
	}

	/**
	 * @return value of TimelineExpectedExecutionEndDate
	 */
	public final java.util.Date getTimelineExpectedExecutionEndDate()
	{
		return getTimelineExpectedExecutionEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of TimelineExpectedExecutionEndDate
	 */
	public final java.util.Date getTimelineExpectedExecutionEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.TimelineExpectedExecutionEndDate.toString());
	}

	/**
	 * Set value of TimelineExpectedExecutionEndDate
	 * @param timelineexpectedexecutionenddate
	 */
	public final void setTimelineExpectedExecutionEndDate(java.util.Date timelineexpectedexecutionenddate)
	{
		setTimelineExpectedExecutionEndDate(getContext(), timelineexpectedexecutionenddate);
	}

	/**
	 * Set value of TimelineExpectedExecutionEndDate
	 * @param context
	 * @param timelineexpectedexecutionenddate
	 */
	public final void setTimelineExpectedExecutionEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timelineexpectedexecutionenddate)
	{
		getMendixObject().setValue(context, MemberNames.TimelineExpectedExecutionEndDate.toString(), timelineexpectedexecutionenddate);
	}

	/**
	 * @return value of TimelineExcpectedDuration
	 */
	public final java.lang.Integer getTimelineExcpectedDuration()
	{
		return getTimelineExcpectedDuration(getContext());
	}

	/**
	 * @param context
	 * @return value of TimelineExcpectedDuration
	 */
	public final java.lang.Integer getTimelineExcpectedDuration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TimelineExcpectedDuration.toString());
	}

	/**
	 * Set value of TimelineExcpectedDuration
	 * @param timelineexcpectedduration
	 */
	public final void setTimelineExcpectedDuration(java.lang.Integer timelineexcpectedduration)
	{
		setTimelineExcpectedDuration(getContext(), timelineexcpectedduration);
	}

	/**
	 * Set value of TimelineExcpectedDuration
	 * @param context
	 * @param timelineexcpectedduration
	 */
	public final void setTimelineExcpectedDuration(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer timelineexcpectedduration)
	{
		getMendixObject().setValue(context, MemberNames.TimelineExcpectedDuration.toString(), timelineexcpectedduration);
	}

	/**
	 * @return value of SN
	 */
	public final java.lang.Long getSN()
	{
		return getSN(getContext());
	}

	/**
	 * @param context
	 * @return value of SN
	 */
	public final java.lang.Long getSN(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.SN.toString());
	}

	/**
	 * Set value of SN
	 * @param sn
	 */
	public final void setSN(java.lang.Long sn)
	{
		setSN(getContext(), sn);
	}

	/**
	 * Set value of SN
	 * @param context
	 * @param sn
	 */
	public final void setSN(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long sn)
	{
		getMendixObject().setValue(context, MemberNames.SN.toString(), sn);
	}

	/**
	 * Set value of TryStatus
	 * @param trystatus
	 */
	public final main.proxies.LeadStatusEnum getTryStatus()
	{
		return getTryStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of TryStatus
	 */
	public final main.proxies.LeadStatusEnum getTryStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TryStatus.toString());
		if (obj == null) {
			return null;
		}
		return main.proxies.LeadStatusEnum.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TryStatus
	 * @param trystatus
	 */
	public final void setTryStatus(main.proxies.LeadStatusEnum trystatus)
	{
		setTryStatus(getContext(), trystatus);
	}

	/**
	 * Set value of TryStatus
	 * @param context
	 * @param trystatus
	 */
	public final void setTryStatus(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.LeadStatusEnum trystatus)
	{
		if (trystatus != null) {
			getMendixObject().setValue(context, MemberNames.TryStatus.toString(), trystatus.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.TryStatus.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Lead_Scope
	 */
	public final main.proxies.Scope getLead_Scope() throws com.mendix.core.CoreException
	{
		return getLead_Scope(getContext());
	}

	/**
	 * @param context
	 * @return value of Lead_Scope
	 * @throws com.mendix.core.CoreException
	 */
	public final main.proxies.Scope getLead_Scope(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Scope result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Lead_Scope.toString());
		if (identifier != null) {
			result = main.proxies.Scope.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Lead_Scope
	 * @param lead_scope
	 */
	public final void setLead_Scope(main.proxies.Scope lead_scope)
	{
		setLead_Scope(getContext(), lead_scope);
	}

	/**
	 * Set value of Lead_Scope
	 * @param context
	 * @param lead_scope
	 */
	public final void setLead_Scope(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Scope lead_scope)
	{
		if (lead_scope == null) {
			getMendixObject().setValue(context, MemberNames.Lead_Scope.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Lead_Scope.toString(), lead_scope.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Lead_Probability
	 */
	public final main.proxies.Probability getLead_Probability() throws com.mendix.core.CoreException
	{
		return getLead_Probability(getContext());
	}

	/**
	 * @param context
	 * @return value of Lead_Probability
	 * @throws com.mendix.core.CoreException
	 */
	public final main.proxies.Probability getLead_Probability(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Probability result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Lead_Probability.toString());
		if (identifier != null) {
			result = main.proxies.Probability.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Lead_Probability
	 * @param lead_probability
	 */
	public final void setLead_Probability(main.proxies.Probability lead_probability)
	{
		setLead_Probability(getContext(), lead_probability);
	}

	/**
	 * Set value of Lead_Probability
	 * @param context
	 * @param lead_probability
	 */
	public final void setLead_Probability(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Probability lead_probability)
	{
		if (lead_probability == null) {
			getMendixObject().setValue(context, MemberNames.Lead_Probability.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Lead_Probability.toString(), lead_probability.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Lead_ProjectOwner
	 */
	public final main.proxies.ProjectOwner getLead_ProjectOwner() throws com.mendix.core.CoreException
	{
		return getLead_ProjectOwner(getContext());
	}

	/**
	 * @param context
	 * @return value of Lead_ProjectOwner
	 * @throws com.mendix.core.CoreException
	 */
	public final main.proxies.ProjectOwner getLead_ProjectOwner(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.ProjectOwner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Lead_ProjectOwner.toString());
		if (identifier != null) {
			result = main.proxies.ProjectOwner.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Lead_ProjectOwner
	 * @param lead_projectowner
	 */
	public final void setLead_ProjectOwner(main.proxies.ProjectOwner lead_projectowner)
	{
		setLead_ProjectOwner(getContext(), lead_projectowner);
	}

	/**
	 * Set value of Lead_ProjectOwner
	 * @param context
	 * @param lead_projectowner
	 */
	public final void setLead_ProjectOwner(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.ProjectOwner lead_projectowner)
	{
		if (lead_projectowner == null) {
			getMendixObject().setValue(context, MemberNames.Lead_ProjectOwner.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Lead_ProjectOwner.toString(), lead_projectowner.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Lead_ContractType
	 */
	public final main.proxies.ContractType getLead_ContractType() throws com.mendix.core.CoreException
	{
		return getLead_ContractType(getContext());
	}

	/**
	 * @param context
	 * @return value of Lead_ContractType
	 * @throws com.mendix.core.CoreException
	 */
	public final main.proxies.ContractType getLead_ContractType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.ContractType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Lead_ContractType.toString());
		if (identifier != null) {
			result = main.proxies.ContractType.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Lead_ContractType
	 * @param lead_contracttype
	 */
	public final void setLead_ContractType(main.proxies.ContractType lead_contracttype)
	{
		setLead_ContractType(getContext(), lead_contracttype);
	}

	/**
	 * Set value of Lead_ContractType
	 * @param context
	 * @param lead_contracttype
	 */
	public final void setLead_ContractType(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.ContractType lead_contracttype)
	{
		if (lead_contracttype == null) {
			getMendixObject().setValue(context, MemberNames.Lead_ContractType.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Lead_ContractType.toString(), lead_contracttype.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Lead_Industry
	 */
	public final main.proxies.Industry getLead_Industry() throws com.mendix.core.CoreException
	{
		return getLead_Industry(getContext());
	}

	/**
	 * @param context
	 * @return value of Lead_Industry
	 * @throws com.mendix.core.CoreException
	 */
	public final main.proxies.Industry getLead_Industry(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Industry result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Lead_Industry.toString());
		if (identifier != null) {
			result = main.proxies.Industry.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Lead_Industry
	 * @param lead_industry
	 */
	public final void setLead_Industry(main.proxies.Industry lead_industry)
	{
		setLead_Industry(getContext(), lead_industry);
	}

	/**
	 * Set value of Lead_Industry
	 * @param context
	 * @param lead_industry
	 */
	public final void setLead_Industry(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Industry lead_industry)
	{
		if (lead_industry == null) {
			getMendixObject().setValue(context, MemberNames.Lead_Industry.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Lead_Industry.toString(), lead_industry.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Lead_Status
	 */
	public final main.proxies.Status getLead_Status() throws com.mendix.core.CoreException
	{
		return getLead_Status(getContext());
	}

	/**
	 * @param context
	 * @return value of Lead_Status
	 * @throws com.mendix.core.CoreException
	 */
	public final main.proxies.Status getLead_Status(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Status result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Lead_Status.toString());
		if (identifier != null) {
			result = main.proxies.Status.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Lead_Status
	 * @param lead_status
	 */
	public final void setLead_Status(main.proxies.Status lead_status)
	{
		setLead_Status(getContext(), lead_status);
	}

	/**
	 * Set value of Lead_Status
	 * @param context
	 * @param lead_status
	 */
	public final void setLead_Status(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Status lead_status)
	{
		if (lead_status == null) {
			getMendixObject().setValue(context, MemberNames.Lead_Status.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Lead_Status.toString(), lead_status.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return leadMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.Lead that = (main.proxies.Lead) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
