// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class LeadChangeLog
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject leadChangeLogMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.LeadChangeLog";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Table("Table"),
		Proccess("Proccess"),
		Attribute("Attribute"),
		OldData("OldData"),
		NewData("NewData"),
		LeadChangeLog_Lead("Main.LeadChangeLog_Lead");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public LeadChangeLog(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected LeadChangeLog(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject leadChangeLogMendixObject)
	{
		if (leadChangeLogMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, leadChangeLogMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.leadChangeLogMendixObject = leadChangeLogMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'LeadChangeLog.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static main.proxies.LeadChangeLog initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.LeadChangeLog.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static main.proxies.LeadChangeLog initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.LeadChangeLog(context, mendixObject);
	}

	public static main.proxies.LeadChangeLog load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.LeadChangeLog.initialize(context, mendixObject);
	}

	public static java.util.List<main.proxies.LeadChangeLog> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> main.proxies.LeadChangeLog.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Table
	 */
	public final java.lang.String getTable()
	{
		return getTable(getContext());
	}

	/**
	 * @param context
	 * @return value of Table
	 */
	public final java.lang.String getTable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Table.toString());
	}

	/**
	 * Set value of Table
	 * @param table
	 */
	public final void setTable(java.lang.String table)
	{
		setTable(getContext(), table);
	}

	/**
	 * Set value of Table
	 * @param context
	 * @param table
	 */
	public final void setTable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String table)
	{
		getMendixObject().setValue(context, MemberNames.Table.toString(), table);
	}

	/**
	 * @return value of Proccess
	 */
	public final java.lang.String getProccess()
	{
		return getProccess(getContext());
	}

	/**
	 * @param context
	 * @return value of Proccess
	 */
	public final java.lang.String getProccess(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Proccess.toString());
	}

	/**
	 * Set value of Proccess
	 * @param proccess
	 */
	public final void setProccess(java.lang.String proccess)
	{
		setProccess(getContext(), proccess);
	}

	/**
	 * Set value of Proccess
	 * @param context
	 * @param proccess
	 */
	public final void setProccess(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String proccess)
	{
		getMendixObject().setValue(context, MemberNames.Proccess.toString(), proccess);
	}

	/**
	 * @return value of Attribute
	 */
	public final java.lang.String getAttribute()
	{
		return getAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of Attribute
	 */
	public final java.lang.String getAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Attribute.toString());
	}

	/**
	 * Set value of Attribute
	 * @param attribute
	 */
	public final void setAttribute(java.lang.String attribute)
	{
		setAttribute(getContext(), attribute);
	}

	/**
	 * Set value of Attribute
	 * @param context
	 * @param attribute
	 */
	public final void setAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attribute)
	{
		getMendixObject().setValue(context, MemberNames.Attribute.toString(), attribute);
	}

	/**
	 * @return value of OldData
	 */
	public final java.lang.String getOldData()
	{
		return getOldData(getContext());
	}

	/**
	 * @param context
	 * @return value of OldData
	 */
	public final java.lang.String getOldData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OldData.toString());
	}

	/**
	 * Set value of OldData
	 * @param olddata
	 */
	public final void setOldData(java.lang.String olddata)
	{
		setOldData(getContext(), olddata);
	}

	/**
	 * Set value of OldData
	 * @param context
	 * @param olddata
	 */
	public final void setOldData(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String olddata)
	{
		getMendixObject().setValue(context, MemberNames.OldData.toString(), olddata);
	}

	/**
	 * @return value of NewData
	 */
	public final java.lang.String getNewData()
	{
		return getNewData(getContext());
	}

	/**
	 * @param context
	 * @return value of NewData
	 */
	public final java.lang.String getNewData(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NewData.toString());
	}

	/**
	 * Set value of NewData
	 * @param newdata
	 */
	public final void setNewData(java.lang.String newdata)
	{
		setNewData(getContext(), newdata);
	}

	/**
	 * Set value of NewData
	 * @param context
	 * @param newdata
	 */
	public final void setNewData(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String newdata)
	{
		getMendixObject().setValue(context, MemberNames.NewData.toString(), newdata);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of LeadChangeLog_Lead
	 */
	public final main.proxies.Lead getLeadChangeLog_Lead() throws com.mendix.core.CoreException
	{
		return getLeadChangeLog_Lead(getContext());
	}

	/**
	 * @param context
	 * @return value of LeadChangeLog_Lead
	 * @throws com.mendix.core.CoreException
	 */
	public final main.proxies.Lead getLeadChangeLog_Lead(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Lead result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.LeadChangeLog_Lead.toString());
		if (identifier != null) {
			result = main.proxies.Lead.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of LeadChangeLog_Lead
	 * @param leadchangelog_lead
	 */
	public final void setLeadChangeLog_Lead(main.proxies.Lead leadchangelog_lead)
	{
		setLeadChangeLog_Lead(getContext(), leadchangelog_lead);
	}

	/**
	 * Set value of LeadChangeLog_Lead
	 * @param context
	 * @param leadchangelog_lead
	 */
	public final void setLeadChangeLog_Lead(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Lead leadchangelog_lead)
	{
		if (leadchangelog_lead == null) {
			getMendixObject().setValue(context, MemberNames.LeadChangeLog_Lead.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.LeadChangeLog_Lead.toString(), leadchangelog_lead.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return leadChangeLogMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.LeadChangeLog that = (main.proxies.LeadChangeLog) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
