// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class Link
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject linkMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.Link";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Link("Link"),
		DisplayText("DisplayText"),
		Link_Lead("Main.Link_Lead");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Link(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Link(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject linkMendixObject)
	{
		if (linkMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, linkMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.linkMendixObject = linkMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Link.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static main.proxies.Link initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.Link.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static main.proxies.Link initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.Link(context, mendixObject);
	}

	public static main.proxies.Link load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.Link.initialize(context, mendixObject);
	}

	public static java.util.List<main.proxies.Link> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> main.proxies.Link.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Link
	 */
	public final java.lang.String getLink()
	{
		return getLink(getContext());
	}

	/**
	 * @param context
	 * @return value of Link
	 */
	public final java.lang.String getLink(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Link.toString());
	}

	/**
	 * Set value of Link
	 * @param link
	 */
	public final void setLink(java.lang.String link)
	{
		setLink(getContext(), link);
	}

	/**
	 * Set value of Link
	 * @param context
	 * @param link
	 */
	public final void setLink(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String link)
	{
		getMendixObject().setValue(context, MemberNames.Link.toString(), link);
	}

	/**
	 * @return value of DisplayText
	 */
	public final java.lang.String getDisplayText()
	{
		return getDisplayText(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayText
	 */
	public final java.lang.String getDisplayText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DisplayText.toString());
	}

	/**
	 * Set value of DisplayText
	 * @param displaytext
	 */
	public final void setDisplayText(java.lang.String displaytext)
	{
		setDisplayText(getContext(), displaytext);
	}

	/**
	 * Set value of DisplayText
	 * @param context
	 * @param displaytext
	 */
	public final void setDisplayText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String displaytext)
	{
		getMendixObject().setValue(context, MemberNames.DisplayText.toString(), displaytext);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Link_Lead
	 */
	public final main.proxies.Lead getLink_Lead() throws com.mendix.core.CoreException
	{
		return getLink_Lead(getContext());
	}

	/**
	 * @param context
	 * @return value of Link_Lead
	 * @throws com.mendix.core.CoreException
	 */
	public final main.proxies.Lead getLink_Lead(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Lead result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Link_Lead.toString());
		if (identifier != null) {
			result = main.proxies.Lead.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Link_Lead
	 * @param link_lead
	 */
	public final void setLink_Lead(main.proxies.Lead link_lead)
	{
		setLink_Lead(getContext(), link_lead);
	}

	/**
	 * Set value of Link_Lead
	 * @param context
	 * @param link_lead
	 */
	public final void setLink_Lead(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Lead link_lead)
	{
		if (link_lead == null) {
			getMendixObject().setValue(context, MemberNames.Link_Lead.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Link_Lead.toString(), link_lead.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return linkMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.Link that = (main.proxies.Link) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
