// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class PersonEnvolved
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject personEnvolvedMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.PersonEnvolved";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Designation("Designation"),
		ContactNumber("ContactNumber"),
		PersonEnvolved_Communication("Main.PersonEnvolved_Communication"),
		PersonEnvolved_Entity("Main.PersonEnvolved_Entity");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PersonEnvolved(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PersonEnvolved(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject personEnvolvedMendixObject)
	{
		if (personEnvolvedMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, personEnvolvedMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.personEnvolvedMendixObject = personEnvolvedMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PersonEnvolved.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static main.proxies.PersonEnvolved initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.PersonEnvolved.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static main.proxies.PersonEnvolved initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.PersonEnvolved(context, mendixObject);
	}

	public static main.proxies.PersonEnvolved load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.PersonEnvolved.initialize(context, mendixObject);
	}

	public static java.util.List<main.proxies.PersonEnvolved> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> main.proxies.PersonEnvolved.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Designation
	 */
	public final java.lang.String getDesignation()
	{
		return getDesignation(getContext());
	}

	/**
	 * @param context
	 * @return value of Designation
	 */
	public final java.lang.String getDesignation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Designation.toString());
	}

	/**
	 * Set value of Designation
	 * @param designation
	 */
	public final void setDesignation(java.lang.String designation)
	{
		setDesignation(getContext(), designation);
	}

	/**
	 * Set value of Designation
	 * @param context
	 * @param designation
	 */
	public final void setDesignation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String designation)
	{
		getMendixObject().setValue(context, MemberNames.Designation.toString(), designation);
	}

	/**
	 * @return value of ContactNumber
	 */
	public final java.lang.String getContactNumber()
	{
		return getContactNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of ContactNumber
	 */
	public final java.lang.String getContactNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContactNumber.toString());
	}

	/**
	 * Set value of ContactNumber
	 * @param contactnumber
	 */
	public final void setContactNumber(java.lang.String contactnumber)
	{
		setContactNumber(getContext(), contactnumber);
	}

	/**
	 * Set value of ContactNumber
	 * @param context
	 * @param contactnumber
	 */
	public final void setContactNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contactnumber)
	{
		getMendixObject().setValue(context, MemberNames.ContactNumber.toString(), contactnumber);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PersonEnvolved_Communication
	 */
	public final main.proxies.Communication getPersonEnvolved_Communication() throws com.mendix.core.CoreException
	{
		return getPersonEnvolved_Communication(getContext());
	}

	/**
	 * @param context
	 * @return value of PersonEnvolved_Communication
	 * @throws com.mendix.core.CoreException
	 */
	public final main.proxies.Communication getPersonEnvolved_Communication(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Communication result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PersonEnvolved_Communication.toString());
		if (identifier != null) {
			result = main.proxies.Communication.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PersonEnvolved_Communication
	 * @param personenvolved_communication
	 */
	public final void setPersonEnvolved_Communication(main.proxies.Communication personenvolved_communication)
	{
		setPersonEnvolved_Communication(getContext(), personenvolved_communication);
	}

	/**
	 * Set value of PersonEnvolved_Communication
	 * @param context
	 * @param personenvolved_communication
	 */
	public final void setPersonEnvolved_Communication(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Communication personenvolved_communication)
	{
		if (personenvolved_communication == null) {
			getMendixObject().setValue(context, MemberNames.PersonEnvolved_Communication.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PersonEnvolved_Communication.toString(), personenvolved_communication.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PersonEnvolved_Entity
	 */
	public final main.proxies.Entity getPersonEnvolved_Entity() throws com.mendix.core.CoreException
	{
		return getPersonEnvolved_Entity(getContext());
	}

	/**
	 * @param context
	 * @return value of PersonEnvolved_Entity
	 * @throws com.mendix.core.CoreException
	 */
	public final main.proxies.Entity getPersonEnvolved_Entity(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Entity result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PersonEnvolved_Entity.toString());
		if (identifier != null) {
			result = main.proxies.Entity.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PersonEnvolved_Entity
	 * @param personenvolved_entity
	 */
	public final void setPersonEnvolved_Entity(main.proxies.Entity personenvolved_entity)
	{
		setPersonEnvolved_Entity(getContext(), personenvolved_entity);
	}

	/**
	 * Set value of PersonEnvolved_Entity
	 * @param context
	 * @param personenvolved_entity
	 */
	public final void setPersonEnvolved_Entity(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Entity personenvolved_entity)
	{
		if (personenvolved_entity == null) {
			getMendixObject().setValue(context, MemberNames.PersonEnvolved_Entity.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PersonEnvolved_Entity.toString(), personenvolved_entity.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return personEnvolvedMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.PersonEnvolved that = (main.proxies.PersonEnvolved) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
