// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class PriceOverview
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject priceOverviewMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.PriceOverview";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AttributeName("AttributeName"),
		AttributeValue("AttributeValue"),
		Version("Version"),
		PriceOverview_Lead("Main.PriceOverview_Lead");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PriceOverview(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PriceOverview(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject priceOverviewMendixObject)
	{
		if (priceOverviewMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, priceOverviewMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.priceOverviewMendixObject = priceOverviewMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'PriceOverview.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static main.proxies.PriceOverview initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.PriceOverview.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static main.proxies.PriceOverview initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.PriceOverview(context, mendixObject);
	}

	public static main.proxies.PriceOverview load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.PriceOverview.initialize(context, mendixObject);
	}

	public static java.util.List<main.proxies.PriceOverview> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> main.proxies.PriceOverview.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of AttributeName
	 */
	public final java.lang.String getAttributeName()
	{
		return getAttributeName(getContext());
	}

	/**
	 * @param context
	 * @return value of AttributeName
	 */
	public final java.lang.String getAttributeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AttributeName.toString());
	}

	/**
	 * Set value of AttributeName
	 * @param attributename
	 */
	public final void setAttributeName(java.lang.String attributename)
	{
		setAttributeName(getContext(), attributename);
	}

	/**
	 * Set value of AttributeName
	 * @param context
	 * @param attributename
	 */
	public final void setAttributeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attributename)
	{
		getMendixObject().setValue(context, MemberNames.AttributeName.toString(), attributename);
	}

	/**
	 * @return value of AttributeValue
	 */
	public final java.math.BigDecimal getAttributeValue()
	{
		return getAttributeValue(getContext());
	}

	/**
	 * @param context
	 * @return value of AttributeValue
	 */
	public final java.math.BigDecimal getAttributeValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.AttributeValue.toString());
	}

	/**
	 * Set value of AttributeValue
	 * @param attributevalue
	 */
	public final void setAttributeValue(java.math.BigDecimal attributevalue)
	{
		setAttributeValue(getContext(), attributevalue);
	}

	/**
	 * Set value of AttributeValue
	 * @param context
	 * @param attributevalue
	 */
	public final void setAttributeValue(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal attributevalue)
	{
		getMendixObject().setValue(context, MemberNames.AttributeValue.toString(), attributevalue);
	}

	/**
	 * @return value of Version
	 */
	public final java.lang.Integer getVersion()
	{
		return getVersion(getContext());
	}

	/**
	 * @param context
	 * @return value of Version
	 */
	public final java.lang.Integer getVersion(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Version.toString());
	}

	/**
	 * Set value of Version
	 * @param version
	 */
	public final void setVersion(java.lang.Integer version)
	{
		setVersion(getContext(), version);
	}

	/**
	 * Set value of Version
	 * @param context
	 * @param version
	 */
	public final void setVersion(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer version)
	{
		getMendixObject().setValue(context, MemberNames.Version.toString(), version);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of PriceOverview_Lead
	 */
	public final main.proxies.Lead getPriceOverview_Lead() throws com.mendix.core.CoreException
	{
		return getPriceOverview_Lead(getContext());
	}

	/**
	 * @param context
	 * @return value of PriceOverview_Lead
	 * @throws com.mendix.core.CoreException
	 */
	public final main.proxies.Lead getPriceOverview_Lead(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.Lead result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.PriceOverview_Lead.toString());
		if (identifier != null) {
			result = main.proxies.Lead.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of PriceOverview_Lead
	 * @param priceoverview_lead
	 */
	public final void setPriceOverview_Lead(main.proxies.Lead priceoverview_lead)
	{
		setPriceOverview_Lead(getContext(), priceoverview_lead);
	}

	/**
	 * Set value of PriceOverview_Lead
	 * @param context
	 * @param priceoverview_lead
	 */
	public final void setPriceOverview_Lead(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.Lead priceoverview_lead)
	{
		if (priceoverview_lead == null) {
			getMendixObject().setValue(context, MemberNames.PriceOverview_Lead.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.PriceOverview_Lead.toString(), priceoverview_lead.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return priceOverviewMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.PriceOverview that = (main.proxies.PriceOverview) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
