// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies;

public class Role
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject roleMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Main.Role";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Role_InvolvedParties_Host("Main.Role_InvolvedParties_Host"),
		Role_InvolvedParties_Invitee("Main.Role_InvolvedParties_Invitee");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Role(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Role(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject roleMendixObject)
	{
		if (roleMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, roleMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.roleMendixObject = roleMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Role.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static main.proxies.Role initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return main.proxies.Role.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static main.proxies.Role initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new main.proxies.Role(context, mendixObject);
	}

	public static main.proxies.Role load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return main.proxies.Role.initialize(context, mendixObject);
	}

	public static java.util.List<main.proxies.Role> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> main.proxies.Role.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Role_InvolvedParties_Host
	 */
	public final main.proxies.InvolvedParties getRole_InvolvedParties_Host() throws com.mendix.core.CoreException
	{
		return getRole_InvolvedParties_Host(getContext());
	}

	/**
	 * @param context
	 * @return value of Role_InvolvedParties_Host
	 * @throws com.mendix.core.CoreException
	 */
	public final main.proxies.InvolvedParties getRole_InvolvedParties_Host(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.InvolvedParties result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Role_InvolvedParties_Host.toString());
		if (identifier != null) {
			result = main.proxies.InvolvedParties.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Role_InvolvedParties_Host
	 * @param role_involvedparties_host
	 */
	public final void setRole_InvolvedParties_Host(main.proxies.InvolvedParties role_involvedparties_host)
	{
		setRole_InvolvedParties_Host(getContext(), role_involvedparties_host);
	}

	/**
	 * Set value of Role_InvolvedParties_Host
	 * @param context
	 * @param role_involvedparties_host
	 */
	public final void setRole_InvolvedParties_Host(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.InvolvedParties role_involvedparties_host)
	{
		if (role_involvedparties_host == null) {
			getMendixObject().setValue(context, MemberNames.Role_InvolvedParties_Host.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Role_InvolvedParties_Host.toString(), role_involvedparties_host.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Role_InvolvedParties_Invitee
	 */
	public final main.proxies.InvolvedParties getRole_InvolvedParties_Invitee() throws com.mendix.core.CoreException
	{
		return getRole_InvolvedParties_Invitee(getContext());
	}

	/**
	 * @param context
	 * @return value of Role_InvolvedParties_Invitee
	 * @throws com.mendix.core.CoreException
	 */
	public final main.proxies.InvolvedParties getRole_InvolvedParties_Invitee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		main.proxies.InvolvedParties result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Role_InvolvedParties_Invitee.toString());
		if (identifier != null) {
			result = main.proxies.InvolvedParties.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Role_InvolvedParties_Invitee
	 * @param role_involvedparties_invitee
	 */
	public final void setRole_InvolvedParties_Invitee(main.proxies.InvolvedParties role_involvedparties_invitee)
	{
		setRole_InvolvedParties_Invitee(getContext(), role_involvedparties_invitee);
	}

	/**
	 * Set value of Role_InvolvedParties_Invitee
	 * @param context
	 * @param role_involvedparties_invitee
	 */
	public final void setRole_InvolvedParties_Invitee(com.mendix.systemwideinterfaces.core.IContext context, main.proxies.InvolvedParties role_involvedparties_invitee)
	{
		if (role_involvedparties_invitee == null) {
			getMendixObject().setValue(context, MemberNames.Role_InvolvedParties_Invitee.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Role_InvolvedParties_Invitee.toString(), role_involvedparties_invitee.getMendixObject().getId());
		}
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return roleMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final main.proxies.Role that = (main.proxies.Role) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
