// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package main.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the Main module
	public static void aCT_AwardedDateGreterBCD(IContext context, main.proxies.Lead _lead)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Lead", _lead == null ? null : _lead.getMendixObject());
		Core.microflowCall("Main.ACT_AwardedDateGreterBCD").withParams(params).execute(context);
	}
	public static void aCT_BCDDateGreterExternalBCD(IContext context, main.proxies.Lead _lead)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Lead", _lead == null ? null : _lead.getMendixObject());
		Core.microflowCall("Main.ACT_BCDDateGreterExternalBCD").withParams(params).execute(context);
	}
	public static void aCT_DescriptionUpdate(IContext context, main.proxies.Lead _lead)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Lead", _lead == null ? null : _lead.getMendixObject());
		Core.microflowCall("Main.ACT_DescriptionUpdate").withParams(params).execute(context);
	}
	public static void aCT_DetailsUpdate(IContext context, main.proxies.Lead _lead)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Lead", _lead == null ? null : _lead.getMendixObject());
		Core.microflowCall("Main.ACT_DetailsUpdate").withParams(params).execute(context);
	}
	public static void aCT_LeadNew(IContext context, main.proxies.Lead _lead)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Lead", _lead == null ? null : _lead.getMendixObject());
		Core.microflowCall("Main.ACT_LeadNew").withParams(params).execute(context);
	}
	public static void aCT_PriceUpdate(IContext context, main.proxies.Lead _lead)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Lead", _lead == null ? null : _lead.getMendixObject());
		Core.microflowCall("Main.ACT_PriceUpdate").withParams(params).execute(context);
	}
	public static void aCT_SetDuration(IContext context, main.proxies.Lead _lead)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Lead", _lead == null ? null : _lead.getMendixObject());
		Core.microflowCall("Main.ACT_SetDuration").withParams(params).execute(context);
	}
	public static void aCT_ShowNewLeadPage(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Main.ACT_ShowNewLeadPage").withParams(params).execute(context);
	}
	public static void aCT_TimelineUpdate(IContext context, main.proxies.Lead _lead)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Lead", _lead == null ? null : _lead.getMendixObject());
		Core.microflowCall("Main.ACT_TimelineUpdate").withParams(params).execute(context);
	}
}
